POLICIES = {
    "allow_internet_without_admin": False,
    "allow_environment_modification": False,
    "allow_outside_project_writes": False,
    "allow_release_without_admin": False,
    "allowed_subprocess_commands": [
        "git",
        "python",
        "pytest",
        "gradle",
        "gradlew",
        "adb",
        "emulator",
    ],
    "blocked_path_prefixes": [
        "/",
        "~",
    ],
    "protected_filenames": [
        ".env",
        ".env.local",
    ],
    "allowed_read_patterns": [
        "*.py",
        "*.md",
        "*.txt",
        "*.yaml",
        "*.yml",
        "*.json",
        "*.kv",
        "*.toml",
        ".env.example",
        ".gitignore",
    ],
    "secret_env_var_prefixes": [
        "GOOGLE_",
        "GEMINI_",
        "FIREBASE_",
        "PLAY_",
        "ADMOB_",
    ],
}