POLICIES = {
    "allow_internet_without_admin": False,
    "allow_environment_modification": False,
    "allow_outside_project_writes": False,
    "allow_release_without_admin": False,
    "allowed_subprocess_commands": [
        "git",
        "python",
        "python3",
        "python.exe",
        "pytest",
        "gradle",
        "gradlew",
        "adb",
        "emulator",
        "buildozer",
    ],
    "blocked_path_prefixes": [
        "/",
        "~",
    ],
    "protected_filenames": [
        ".env",
        ".env.local",
        "google-services.json",
        "firebase-service-account.json",
    ],
    "editable_roots": [
        "app",
        "app_frameworks",
        "docs",
        "tests",
        "scripts",
        "android",
    ],
    "syntax_check_python_after_write": True,
    "max_changed_files_per_iteration": 12,
    "secret_env_var_prefixes": [
        "GOOGLE_",
        "GEMINI_",
        "FIREBASE_",
        "PLAY_",
        "ADMOB_",
        "OPENAI_",
        "ANDROID_",
    ],
}
